In [49]:
import numpy as np
import sys

class Sudoku:
    def __init__(self, grid=None):
        self.grid = grid
        self.rec_count = 0
        if grid is not None:
            print("      ---Game---")
            print(self.grid)
    def newGame(self, num):
        #creates game with number "num" filled tiles
        self.rec_count = 0
        self.grid = np.zeros((9,9), dtype=int)
        idx = []
        idx0 = tuple(np.random.randint(0,9, size=(2)))
        while len(idx)<num:
            while idx0 in idx:
                idx0 = tuple(np.random.randint(0,9, size=(2)))
            idx.append(idx0)
            choice = list(np.arange(1,10))
            val = choice.pop(np.random.randint(0,9))
            while (not self.possible(idx0[0],idx0[1],val)) and (len(choice)>0):
                if len(choice)>1:
                    val = choice.pop(np.random.randint(1,len(choice)))
                else:
                    val = choice[0]
            self.grid[idx0] = val
        print("    ---New Game---")
        print(self.grid)
        return None
    def possible(self,y,x,n):
        #tests if a number "n" is valid at position "x","y"
        #line
        for i in range(0,9):
            if self.grid[y][i]==n:
                return False
        #column
        for i in range(0,9):
            if self.grid[i][x]==n:
                return False
        #block
        ax, ay = (x//3)*3, (y//3)*3
        for i in range(0,3):
            for j in range(0,3):
                if self.grid[ay+i][ax+j]==n:
                    return False
        #all tests passed
        return True
    def solve(self):
        #loop recursivly over all positions
        self.rec_count += 1
        for y in range(0,9):
            for x in range(0,9):
                #solve if empty entry (0)
                if self.grid[y][x]==0 :
                    #test all possible values
                    for n in range(1,10):
                        if self.possible(y,x,n):
                            self.grid[y][x] = n
                            #if value possible: fill it in and solve with one less unknown
                            self.solve()
                            #returns if no solution possible or solution found and already printed out
                            #-> backtracking
                            self.grid[y][x] = 0
                    return None
        #all elements filled
        print("    ---Solution---")
        print(self.grid)
        print("nr. recursions: ",self.rec_count)
        response = input("do you want another solution ? (y/n)")
        if response!="y":
            sys.exit()
        return None


## generate and solve game
note: not all games have a solution !

In [52]:
MySudoku = Sudoku()
MySudoku.newGame(22)
MySudoku.solve()

    ---New Game---
[[0 7 0 0 0 0 0 0 3]
 [0 0 0 0 0 1 2 0 0]
 [0 0 0 0 0 7 4 0 0]
 [0 1 0 4 0 0 0 0 8]
 [0 0 3 0 0 0 0 0 6]
 [0 4 0 6 0 0 0 7 1]
 [0 0 0 0 8 5 0 3 2]
 [8 0 0 0 0 0 0 0 9]
 [0 0 0 0 7 0 0 0 0]]
    ---Solution---
[[1 7 2 5 4 6 8 9 3]
 [3 5 4 8 9 1 2 6 7]
 [6 8 9 2 3 7 4 1 5]
 [7 1 6 4 5 3 9 2 8]
 [2 9 3 7 1 8 5 4 6]
 [5 4 8 6 2 9 3 7 1]
 [4 6 1 9 8 5 7 3 2]
 [8 2 7 3 6 4 1 5 9]
 [9 3 5 1 7 2 6 8 4]]
nr. recursions:  189
do you want another solution ? (y/n)y
    ---Solution---
[[1 7 2 5 4 6 8 9 3]
 [3 5 4 8 9 1 2 6 7]
 [6 8 9 2 3 7 4 1 5]
 [7 1 6 4 5 3 9 2 8]
 [2 9 3 7 1 8 5 4 6]
 [5 4 8 6 2 9 3 7 1]
 [4 6 7 9 8 5 1 3 2]
 [8 2 1 3 6 4 7 5 9]
 [9 3 5 1 7 2 6 8 4]]
nr. recursions:  219
do you want another solution ? (y/n)y
    ---Solution---
[[1 7 2 5 4 6 8 9 3]
 [3 5 4 8 9 1 2 6 7]
 [6 8 9 2 3 7 4 1 5]
 [7 1 6 4 5 9 3 2 8]
 [2 9 3 7 1 8 5 4 6]
 [5 4 8 6 2 3 9 7 1]
 [4 6 1 9 8 5 7 3 2]
 [8 2 7 3 6 4 1 5 9]
 [9 3 5 1 7 2 6 8 4]]
nr. recursions:  364
do you want another solut

SystemExit: 

## input and solve game

In [51]:
grid = np.array([[5,3,0,0,7,0,0,0,0],
                 [6,0,0,1,9,5,0,0,0],
                 [0,9,8,0,0,0,0,6,0],
                 [8,0,0,0,6,0,0,0,3],
                 [4,0,0,8,0,3,0,0,1],
                 [7,0,0,0,2,0,0,0,6],
                 [0,6,0,0,0,0,2,8,0],
                 [0,0,0,4,1,9,0,0,5],
                 [0,0,0,0,8,0,0,7,9]])
MySudoku = Sudoku(grid)
MySudoku.solve()

      ---Game---
[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]
    ---Solution---
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
nr. recursions:  4209
do you want another solution ? (y/n)y
